### ISSUE TITLE
Running your first job filepath fixes

### ISSUE THREAD

**Issue by mnodini** [behavioral-data/Homekit2020#1]
With the current file setup the model configuration path should be setup like this:

python src/models/train.py fit `# Main entry point` \
        --config src/data/task_configs/PredictFluPos.yaml `# Configures the task`\
        --config configs/models/CNNToTransformerClassifier.yaml `# Configures the model`\
        --data.train_path $PWD/data/processed/split/audere_split_2020_02_10/train_7_day `# Train data location`\
        --data.val_path $PWD/data/processed/split/audere_split_2020_02_10/eval_7_day  `# Validation data location`\

**Comment by mnodini** [comment]
When running the first job there's a bug in train.py

<img width="1193" alt="image" src="https://user-images.githubusercontent.com/77136138/185251398-007c7c38-df71-48c4-860f-d588796d3cbf.png">

This code chunk might need some modifications, unless it's just a problem with my environment.

<img width="461" alt="image" src="https://user-images.githubusercontent.com/77136138/185251666-5018dc0a-f63f-4979-8da9-388241d48191.png">


Traceback (most recent call last):
  File "/cephfs/tempredict-shared-space/pkasl/Homekit2020/src/models/train.py", line 217, in <module>
    cli = CLI(trainer_defaults=trainer_defaults,
  File "/opt/conda/lib/python3.9/site-packages/pytorch_lightning/utilities/cli.py", line 157, in __init__
    super().__init__(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/pytorch_lightning/cli.py", line 339, in __init__
    self.setup_parser(run, main_kwargs, subparser_kwargs)
  File "/opt/conda/lib/python3.9/site-packages/pytorch_lightning/cli.py", line 374, in setup_parser
    self._add_subcommands(self.parser, **subparser_kwargs)
  File "/opt/conda/lib/python3.9/site-packages/pytorch_lightning/cli.py", line 445, in _add_subcommands
    subcommand_parser = self._prepare_subcommand_parser(trainer_class, subcommand, **kwargs.get(subcommand, {}))
  File "/opt/conda/lib/python3.9/site-packages/pytorch_lightning/cli.py", line 453, in _prepare_subcommand_parser
    self._add_arguments(parser)
  File "/opt/conda/lib/python3.9/site-packages/pytorch_lightning/cli.py", line 409, in _add_arguments
    self.add_core_arguments_to_parser(parser)
  File "/opt/conda/lib/python3.9/site-packages/pytorch_lightning/cli.py", line 394, in add_core_arguments_to_parser
    parser.set_defaults(trainer_defaults)
  File "/opt/conda/lib/python3.9/site-packages/jsonargparse/core.py", line 845, in set_defaults
    raise KeyError(f'No action for destination key "{dest}" to set its default.')
KeyError: 'No action for destination key "trainer.checkpoint_callback" to set its default.'

**Comment by TheMikeMerrill** [comment]
Thanks!    The README should be fixed now.
