### ISSUE TITLE
RuntimeError: Unable to find a valid cuDNN algorithm to run convolution

### ISSUE THREAD

**Issue by safranchik** [behavioral-data/Homekit2020#10]
Hello! 

Whenever I run the first job using the updated repo, the program gets loading for ~15 minutes (see the first image). This didn't happen before.

![image](https://user-images.githubusercontent.com/23159096/186326970-637b7b66-58fa-40a1-abba-9ab2181738b5.png)

Further, after the program continues with the execution, I run into the following error:

![image](https://user-images.githubusercontent.com/23159096/186326836-9ffb81ad-7ca5-478f-955a-a651b4770778.png)

(mobs is the nickname of the HomeKit2020 environment)

**Comment by safranchik** [comment]
This is the precise output of the script before it crashes:

```
  | Name          | Type                      | Params
------------------------------------------------------------
0 | train_metrics | TorchMetricClassification | 0
1 | val_metrics   | TorchMetricClassification | 0
2 | test_metrics  | TorchMetricClassification | 0
3 | criterion     | CrossEntropyLoss          | 0
4 | encoder       | CNNToTransformerEncoder   | 43.2 K
5 | head          | ClassificationModule      | 2.6 K
------------------------------------------------------------
45.8 K    Trainable params
0         Non-trainable params
45.8 K    Total params
0.183     Total estimated model params size (MB)
Epoch 0: : 0it [00:00, ?it/s]Traceback (most recent call last):
  File "/mmfs1/gscratch/bdata/estebans/Homekit2020/src/models/train.py", line 200, in <module>
    cli = CLI(trainer_defaults=trainer_defaults,
  File "/gscratch/bdata/estebans/.conda/envs/mobs/lib/python3.9/site-packages/pytorch_lightning/utilities/cli.py", line 157, in __init__
    super().__init__(*args, **kwargs)
  File "/gscratch/bdata/estebans/.conda/envs/mobs/lib/python3.9/site-packages/pytorch_lightning/cli.py", line 350, in __init__
    self._run_subcommand(self.subcommand)
  File "/gscratch/bdata/estebans/.conda/envs/mobs/lib/python3.9/site-packages/pytorch_lightning/cli.py", line 626, in _run_subcommand
    fn(**fn_kwargs)
  File "/gscratch/bdata/estebans/.conda/envs/mobs/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 700, in fit
    self._call_and_handle_interrupt(
  File "/gscratch/bdata/estebans/.conda/envs/mobs/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 654, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/gscratch/bdata/estebans/.conda/envs/mobs/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 741, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/gscratch/bdata/estebans/.conda/envs/mobs/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1166, in _run
    results = self._run_stage()
  File "/gscratch/bdata/estebans/.conda/envs/mobs/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1252, in _run_stage
    return self._run_train()
  File "/gscratch/bdata/estebans/.conda/envs/mobs/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1282, in _run_train
    self.fit_loop.run()
  File "/gscratch/bdata/estebans/.conda/envs/mobs/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/gscratch/bdata/estebans/.conda/envs/mobs/lib/python3.9/site-packages/pytorch_lightning/loops/fit_loop.py", line 269, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "/gscratch/bdata/estebans/.conda/envs/mobs/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/gscratch/bdata/estebans/.conda/envs/mobs/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 203, in advance
    batch_output = self.batch_loop.run(kwargs)
  File "/gscratch/bdata/estebans/.conda/envs/mobs/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/gscratch/bdata/estebans/.conda/envs/mobs/lib/python3.9/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 87, in advance
    outputs = self.optimizer_loop.run(optimizers, kwargs)
  File "/gscratch/bdata/estebans/.conda/envs/mobs/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/gscratch/bdata/estebans/.conda/envs/mobs/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 201, in advance
    result = self._run_optimization(kwargs, self._optimizers[self.optim_progress.optimizer_position])
  File "/gscratch/bdata/estebans/.conda/envs/mobs/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 248, in _run_optimization
    self._optimizer_step(optimizer, opt_idx, kwargs.get("batch_idx", 0), closure)
  File "/gscratch/bdata/estebans/.conda/envs/mobs/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 358, in _optimizer_step
    self.trainer._call_lightning_module_hook(
  File "/gscratch/bdata/estebans/.conda/envs/mobs/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1549, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/mmfs1/gscratch/bdata/estebans/Homekit2020/src/models/models.py", line 290, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/gscratch/bdata/estebans/.conda/envs/mobs/lib/python3.9/site-packages/pytorch_lightning/core/optimizer.py", line 168, in step
    step_output = self._strategy.optimizer_step(self._optimizer, self._optimizer_idx, closure, **kwargs)
  File "/gscratch/bdata/estebans/.conda/envs/mobs/lib/python3.9/site-packages/pytorch_lightning/strategies/strategy.py", line 216, in optimizer_step
    return self.precision_plugin.optimizer_step(model, optimizer, opt_idx, closure, **kwargs)
  File "/gscratch/bdata/estebans/.conda/envs/mobs/lib/python3.9/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 153, in optimizer_step
    return optimizer.step(closure=closure, **kwargs)
  File "/gscratch/bdata/estebans/.conda/envs/mobs/lib/python3.9/site-packages/torch/optim/lr_scheduler.py", line 65, in wrapper
    return wrapped(*args, **kwargs)
  File "/gscratch/bdata/estebans/.conda/envs/mobs/lib/python3.9/site-packages/torch/optim/optimizer.py", line 113, in wrapper
    return func(*args, **kwargs)
  File "/gscratch/bdata/estebans/.conda/envs/mobs/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/gscratch/bdata/estebans/.conda/envs/mobs/lib/python3.9/site-packages/torch/optim/adam.py", line 118, in step
    loss = closure()
  File "/gscratch/bdata/estebans/.conda/envs/mobs/lib/python3.9/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 138, in _wrap_closure
    closure_result = closure()
  File "/gscratch/bdata/estebans/.conda/envs/mobs/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 146, in __call__
    self._result = self.closure(*args, **kwargs)
  File "/gscratch/bdata/estebans/.conda/envs/mobs/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 141, in closure
    self._backward_fn(step_output.closure_loss)
  File "/gscratch/bdata/estebans/.conda/envs/mobs/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 304, in backward_fn
    self.trainer._call_strategy_hook("backward", loss, optimizer, opt_idx)
  File "/gscratch/bdata/estebans/.conda/envs/mobs/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1703, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/gscratch/bdata/estebans/.conda/envs/mobs/lib/python3.9/site-packages/pytorch_lightning/strategies/strategy.py", line 191, in backward
    self.precision_plugin.backward(self.lightning_module, closure_loss, optimizer, optimizer_idx, *args, **kwargs)
  File "/gscratch/bdata/estebans/.conda/envs/mobs/lib/python3.9/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 80, in backward
    model.backward(closure_loss, optimizer, optimizer_idx, *args, **kwargs)
  File "/gscratch/bdata/estebans/.conda/envs/mobs/lib/python3.9/site-packages/pytorch_lightning/core/module.py", line 1411, in backward
    loss.backward(*args, **kwargs)
  File "/gscratch/bdata/estebans/.conda/envs/mobs/lib/python3.9/site-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/gscratch/bdata/estebans/.conda/envs/mobs/lib/python3.9/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Unable to find a valid cuDNN algorithm to run convolution

```


Max VRAM memory used: 1335MiB

**Comment by TheMikeMerrill** [comment]
Closing this because after offline discussion Esteban fixed this by upgrading his `cudatoolkit`
