### ISSUE TITLE
Unable to access CUDA devices while in Conda Environment

### ISSUE THREAD

**Issue by mnodini** [behavioral-data/Homekit2020#14]
In default environment:

<img width="547" alt="image" src="https://user-images.githubusercontent.com/77136138/187547547-8f238dcd-5105-4a1f-862f-54aac6635eb3.png">

In Homekit2020 environment w/ cudatoolkit version 10.2:

<img width="821" alt="image" src="https://user-images.githubusercontent.com/77136138/187547610-95ff8a89-277a-48a1-abe4-7630b59e3f7d.png">

In "base" environment:

<img width="565" alt="image" src="https://user-images.githubusercontent.com/77136138/187548783-2553e9ec-9db6-4836-9786-78f4b0ea92d4.png">

In Homekit2020 environment w/ cudatoolkit version 11.6.0

<img width="1241" alt="image" src="https://user-images.githubusercontent.com/77136138/187551391-292669af-be59-437b-b681-ea3c0e0dea46.png">

<img width="832" alt="image" src="https://user-images.githubusercontent.com/77136138/187551531-4e3e29cd-a432-40ea-b4a0-533f97772a2c.png">

**Comment by mnodini** [comment]
After creating the conda environment, but before running "pip install -e" CUDA devices are able to be accessed

<img width="1125" alt="image" src="https://user-images.githubusercontent.com/77136138/188009677-73091913-d9bf-4435-a0c4-7d7b93997fbe.png">

**Comment by TheMikeMerrill** [comment]
This is really interesting. Just to be clear, it looks like installing the `src` module causes the environment to lose contact with the GPUs? 

In the second example, it looks like you try launching `src/models/train.py` with `python`. Can you try it with `python3`?

**Comment by mnodini** [comment]
Before pip install -e .

```
(Homekit2020) jovyan@jupyter-mnodini-40ucsd-2eedu:~/Homekit2020$ python3 src/models/train.py fit `# Main entry point` \
>         --config configs/tasks/HomekitPredictFluPos.yaml `# Configures the task`\
>         --config configs/models/CNNToTransformerClassifier.yaml `# Configures the model`\
>         --data.train_path  $PWD/data/processed/split/audere_split_2020_02_10/train_7_day  `# Train data location`\
>         --data.val_path $PWD/data/processed/split/audere_split_2020_02_10/eval_7_day  `# Validation data location`\
> 
/opt/conda/envs/Homekit2020/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: /opt/conda/envs/Homekit2020/lib/python3.9/site-packages/torchvision/image.so: undefined symbol: _ZN3c106detail19maybe_wrap_dim_slowEllb
  warn(f"Failed to load image Python extension: {e}")
Traceback (most recent call last):
  File "/home/jovyan/Homekit2020/src/models/train.py", line 22, in <module>
    from src.models.tasks import get_task_with_name
ModuleNotFoundError: No module named 'src'

```

After

```
(Homekit2020) jovyan@jupyter-mnodini-40ucsd-2eedu:~/Homekit2020$ python3 src/models/train.py fit `# Main entry point` \
>         --config configs/tasks/HomekitPredictFluPos.yaml `# Configures the task`\
>         --config configs/models/CNNToTransformerClassifier.yaml `# Configures the model`\
>         --data.train_path  $PWD/data/processed/split/audere_split_2020_02_10/train_7_day  `# Train data location`\
>         --data.val_path $PWD/data/processed/split/audere_split_2020_02_10/eval_7_day  `# Validation data location`\
> 
/opt/conda/envs/Homekit2020/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: /opt/conda/envs/Homekit2020/lib/python3.9/site-packages/torchvision/image.so: undefined symbol: _ZN3c106detail19maybe_wrap_dim_slowEllb
  warn(f"Failed to load image Python extension: {e}")
Traceback (most recent call last):
  File "/home/jovyan/Homekit2020/src/models/train.py", line 22, in <module>
    from src.models.tasks import get_task_with_name
ModuleNotFoundError: No module named 'src'
(Homekit2020) jovyan@jupyter-mnodini-40ucsd-2eedu:~/Homekit2020$ pip install -e .
Obtaining file:///home/jovyan/Homekit2020
  Preparing metadata (setup.py) ... done
Installing collected packages: src
  Running setup.py develop for src
Successfully installed src-0.1.0
(Homekit2020) jovyan@jupyter-mnodini-40ucsd-2eedu:~/Homekit2020$ python3 src/models/train.py fit `# Main entry point`         --config configs/tasks/HomekitPredictFluPos.yaml `# Configures the task`        --config configs/models/CNNToTransformerClassifier.yaml `# Configures the model`        --data.train_path  $PWD/data/processed/split/audere_split_2020_02_10/train_7_day  `# Train data location`        --data.val_path $PWD/data/processed/split/audere_split_2020_02_10/eval_7_day  `# Validation data location`\
> 
/opt/conda/envs/Homekit2020/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: /opt/conda/envs/Homekit2020/lib/python3.9/site-packages/torchvision/image.so: undefined symbol: _ZN3c106detail19maybe_wrap_dim_slowEllb
  warn(f"Failed to load image Python extension: {e}")
```

**Comment by mnodini** [comment]
> This is really interesting. Just to be clear, it looks like installing the `src` module causes the environment to lose contact with the GPUs?
Yeah it seems like that's the case, I thought it might be inaccessible from any newly created conda environment; but, I created a testEnv and installed cudatoolkit and it's still able to access the GPUs

```
(testEnv) jovyan@jupyter-mnodini-40ucsd-2eedu:~$ conda list
# packages in environment at /opt/conda/envs/testEnv:
#
# Name                    Version                   Build  Channel
(testEnv) jovyan@jupyter-mnodini-40ucsd-2eedu:~$ conda install cudatoolkit
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.12.0
  latest version: 4.14.0

Please update conda by running

    $ conda update -n base conda



## Package Plan ##

  environment location: /opt/conda/envs/testEnv

  added / updated specs:
    - cudatoolkit


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    _openmp_mutex-4.5          |            2_gnu          23 KB  conda-forge
    cudatoolkit-11.7.0         |      hd8887f6_10       831.6 MB  conda-forge
    libgomp-12.1.0             |      h8d9b700_16         459 KB  conda-forge
    ------------------------------------------------------------
                                           Total:       832.1 MB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-conda_forge
  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-2_gnu
  cudatoolkit        conda-forge/linux-64::cudatoolkit-11.7.0-hd8887f6_10
  libgcc-ng          conda-forge/linux-64::libgcc-ng-12.1.0-h8d9b700_16
  libgomp            conda-forge/linux-64::libgomp-12.1.0-h8d9b700_16
  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-12.1.0-ha89aaad_16


Proceed ([y]/n)? y


Downloading and Extracting Packages
_openmp_mutex-4.5    | 23 KB     | ###################################################################################################################### | 100% 
cudatoolkit-11.7.0   | 831.6 MB  | #####################################################################################################################6 | 100% 
cudatoolkit-11.7.0   | 831.6 MB  | ###################################################################################################################### | 100% 
libgomp-12.1.0       | 459 KB    | ###################################################################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: / By downloading and using the CUDA Toolkit conda packages, you accept the terms and conditions of the CUDA End User License Agreement (EULA): https://docs.nvidia.com/cuda/eula/index.html

done
(testEnv) jovyan@jupyter-mnodini-40ucsd-2eedu:~$ 
(testEnv) jovyan@jupyter-mnodini-40ucsd-2eedu:~$ python3
Python 3.9.10 | packaged by conda-forge | (main, Feb  1 2022, 21:24:11) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torcch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'torcch'
>>> import torch
>>> exit()
(testEnv) jovyan@jupyter-mnodini-40ucsd-2eedu:~$ python3
Python 3.9.10 | packaged by conda-forge | (main, Feb  1 2022, 21:24:11) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.is_available()
True
>>>

**Comment by TheMikeMerrill** [comment]
I'm not able to duplicate this. What happens if you try to install any other package with `pip install -e .`? Could you try making a dummy package and installing it that way? That would help me figure out if the bug is specific to homekit2020.

**Comment by mnodini** [comment]
I think the problem was with the model of GPU being loaded into my instance. I've found when using NVIDIA GeForce RTX 2080 TI, I'm able to access the GPUs from within the conda environment. Do you know what GPUs are typically used for Homekit2020?

**Comment by TheMikeMerrill** [comment]
That's odd - it should run fine on a 2080Ti. We have a few of those in the bdata lab and it hasn't been an issue in the past. It could be an issue with your local CUDA drivers, but I'm just speculating here. I'm going to close this issue and will reopen if anyone has similar problems.
