### ISSUE TITLE
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType' when running First Job

### ISSUE THREAD

**Issue by mnodini** [behavioral-data/Homekit2020#15]
```

(Homekit2020) jovyan@jupyter-mnodini-40ucsd-2eedu:~/Homekit2020$ python3 src/models/train.py fit `# Main entry point` \
>         --config configs/tasks/HomekitPredictFluPos.yaml `# Configures the task`\
>         --config configs/models/CNNToTransformerClassifier.yaml `# Configures the model`\
>         --data.train_path  $PWD/data/processed/split/audere_split_2020_02_10/train_7_day  `# Train data location`\
>         --data.val_path $PWD/data/processed/split/audere_split_2020_02_10/eval_7_day  `# Validation data location`\
> 
Global seed set to 999
09/02/2022 21:40:15 - INFO - src.data.utils -   Reading lab_results_with_triggerdate...
Traceback (most recent call last):
  File "/home/jovyan/Homekit2020/src/models/train.py", line 200, in <module>
    cli = CLI(trainer_defaults=trainer_defaults,
  File "/opt/conda/envs/Homekit2020/lib/python3.9/site-packages/pytorch_lightning/utilities/cli.py", line 157, in __init__
    super().__init__(*args, **kwargs)
  File "/opt/conda/envs/Homekit2020/lib/python3.9/site-packages/pytorch_lightning/cli.py", line 347, in __init__
    self.instantiate_classes()
  File "/opt/conda/envs/Homekit2020/lib/python3.9/site-packages/pytorch_lightning/cli.py", line 483, in instantiate_classes
    self.config_init = self.parser.instantiate_classes(self.config)
  File "/opt/conda/envs/Homekit2020/lib/python3.9/site-packages/jsonargparse/deprecated.py", line 127, in patched_instantiate_classes
    cfg = self._unpatched_instantiate_classes(cfg, **kwargs)
  File "/opt/conda/envs/Homekit2020/lib/python3.9/site-packages/jsonargparse/core.py", line 1089, in instantiate_classes
    cfg[subcommand] = subparser.instantiate_classes(cfg[subcommand], instantiate_groups=instantiate_groups)
  File "/opt/conda/envs/Homekit2020/lib/python3.9/site-packages/jsonargparse/deprecated.py", line 127, in patched_instantiate_classes
    cfg = self._unpatched_instantiate_classes(cfg, **kwargs)
  File "/opt/conda/envs/Homekit2020/lib/python3.9/site-packages/jsonargparse/core.py", line 1080, in instantiate_classes
    parent[key] = component.instantiate_classes(value)
  File "/opt/conda/envs/Homekit2020/lib/python3.9/site-packages/jsonargparse/typehints.py", line 399, in instantiate_classes
    value[num] = adapt_typehints(val, self._typehint, instantiate_classes=True, sub_add_kwargs=sub_add_kwargs)
  File "/opt/conda/envs/Homekit2020/lib/python3.9/site-packages/jsonargparse/typehints.py", line 645, in adapt_typehints
    val = adapt_class_type(val, serialize, instantiate_classes, sub_add_kwargs, prev_val=prev_val)
  File "/opt/conda/envs/Homekit2020/lib/python3.9/site-packages/jsonargparse/typehints.py", line 808, in adapt_class_type
    return val_class(**{**init_args, **dict_kwargs})
  File "/home/jovyan/Homekit2020/src/models/tasks.py", line 496, in __init__
    ActivityTask.__init__(self, fields=fields, activity_level=activity_level,**kwargs)
  File "/home/jovyan/Homekit2020/src/models/tasks.py", line 349, in __init__
    self.data_shape = (int(data_length),len(self.fields))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by TheMikeMerrill** [comment]
@mnodini  were you able to resolve this?

**Comment by TheMikeMerrill** [comment]
This seems to happen on some petastorm datasets when the schema doesn't contain information about the row length. I've been able to replicate it on some datasets, but it doesn't appear when I run jobs on Homekit2020
